SELECT
  *
FROM
  "SALESANALYSIS"."PUBLIC"."ANALYTICS"
LIMIT
  10;
  
---1. Daily Sales Price per Unit

  SELECT
    DATE,
    SALES,
    QUANTITY_SOLD,
    SALES / NULLIF(QUANTITY_SOLD, 0) AS DAILY_UNIT_PRICE
FROM
    "SALESANALYSIS"."PUBLIC"."ANALYTICS"
ORDER BY DATE;

---2. Average Unit Sales Price
SELECT
    AVG(SALES / NULLIF(QUANTITY_SOLD, 0)) AS AVG_UNIT_PRICE
FROM
    "SALESANALYSIS"."PUBLIC"."ANALYTICS";
    
---3. Daily % Gross Profit
SELECT
    DATE,
    SALES,
    COST_OF_SALES,
    ((SALES - COST_OF_SALES) / NULLIF(SALES, 0)) * 100 AS DAILY_GP_PERCENT
FROM
    "SALESANALYSIS"."PUBLIC"."ANALYTICS"
ORDER BY DATE;

---4. Daily % Gross Profit per Unit
SELECT
    DATE,
    (SALES - COST_OF_SALES) / NULLIF(QUANTITY_SOLD, 0) AS GP_PER_UNIT
FROM
    "SALESANALYSIS"."PUBLIC"."ANALYTICS"
ORDER BY DATE;

---5. Price Elasticity of Demand (PED) for 3 Promo Periods
